#!/bin/bash

# Define the configuration file path
CONFIG_FILE="filebeat.yml"

# Elasticsearch IP address
ES_IP="elks.neelareddy.store"

# Create or overwrite the configuration file with the required settings
cat <<EOL > $CONFIG_FILE
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/access.log

output.elasticsearch:
  hosts: ["http://$ES_IP:9200"]
EOL

echo "YAML configuration file created successfully."